image: docker:git
services:
  - docker:dind


stages:
  - dockerize_dev
  - dockerize_QA
  - dockerize_PRO


before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

Dockerize_dev:
  stage: dockerize_dev
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG
  only:
    - develop

Dockerize_QA:
  stage: dockerize_QA
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:qa-$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:qa-$CI_COMMIT_REF_SLUG
  only:
    - quality


Dockerize_PRO:
  stage: dockerize_PRO
  script:
    - docker build --pull -t CI_COMMIT_TAG:prod-$CI_COMMIT_TAG .
    - docker push CI_COMMIT_TAG:prod-$CI_COMMIT_TAG
  only:
    - main

